In [2]:
from sklearn.svm import SVR
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import r2_score
from sklearn import datasets

In [3]:
df = datasets.load_diabetes(as_frame=True).frame

In [4]:
df.head()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6,target
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646,151.0
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204,75.0
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930,141.0
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362,206.0
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641,135.0

In [5]:
x = df.drop("target",axis =1)
y = df["target"]

In [6]:
x.head()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641

In [7]:
x_train,x_test,y_train,y_test = train_test_split(
    x,y,test_size=0.2,random_state=42
)

In [8]:
y_scaler =  StandardScaler()
Y_train = y_scaler.fit_transform(y_train.values.reshape(-1,1)).ravel()
Y_test = y_scaler.fit_transform(y_test.values.reshape(-1,1)).ravel()

In [ ]:
model = SVR()
model.fit(x_train,Y_train)
y_test_pred = model.predict(x_test)
#y_train_pred = model.predict(x_train)

In [22]:
print(f"r2 = {r2_score(Y_test,y_test_pred)}")
#print(f"r2 = {r2_score(Y_test,y_train_pred)}")

r2 = 0.5010065417112928

In [23]:
model_1 = SVR(kernel='linear')
model.fit(x_train,Y_train)
y_test_pred = model.predict(x_test)

In [24]:
model_2 = SVR(kernel="poly")
model.fit(x_train,Y_train)
y_test_pred = model.predict(x_test)

In [26]:
model_3 = SVR(kernel="sigmoid")
model.fit(x_train,Y_train)
y_test_pred = model.predict(x_test)

In [30]:
data = {SVR():"model",
        SVR(kernel="linear") : "model_1",
        SVR(kernel="poly"):"model_2",
        SVR(kernel="sigmoid"):"model_3"
        }

for model,name in data.items():
    model.fit(x_train,Y_train)
    y_test_pred = model.predict(x_test)
    print(f"r2 = {r2_score(Y_test,y_test_pred)} for model = {model}")

r2 = 0.5010065417112928 for model = SVR()
r2 = 0.393633944019984 for model = SVR(kernel='linear')
r2 = 0.31230735388163244 for model = SVR(kernel='poly')
r2 = -20.41677052593262 for model = SVR(kernel='sigmoid')